#!/bin/bash 

if [ $# -lt 1 ] ; then
    echo "usage: $0 <test name>" >&2
    exit 1
fi

cd $(dirname $0)

GUEST_BASE_WORKING_DIR=/root/test-linux-stable

for TEST_NAME in $@ ; do
    export TEST_DIR=${TESTS_DIR}/$TEST_NAME
    export GUEST_TEST_DIR=${GUEST_BASE_WORKING_DIR}/$TEST_NAME
    # deploy test
    scp -rp ${TEST_DIR} ${SSH_USER}@${MACHINE}:${GUEST_BASE_WORKING_DIR}

    if [ -x ${TEST_DIR}/pre-run ] ; then
	. ${TEST_DIR}/pre-run
    fi

    # run test
    ssh ${SSH_USER}@${MACHINE} "cd ${GUEST_TEST_DIR}; make run"
done
