#!/bin/bash

TEST_NAME=build-latest-kernel

GUEST_BASE_WORKING_DIR=/root/test-linux-stable
GUEST_TESTS_DIR=${GUEST_WORKING_DIR}/tests
# deploy test

ssh ${SSH_USER}@${MACHINE} mkdir -p ${GUEST_TESTS_DIR}
scp ${TESTS_DIR}/${TEST_NAME} ${SSH_USER}@${MACHINE}:${GUEST_TESTS_DIR}
scp ${BASE_WORKING_DIR}/config.base ${SSH_USER}@${MACHINE}:${GUEST_BASE_WORKING_DIR}/config.base

# run test
ssh ${SSH_USER}@${MACHINE} "cd ${GUEST_BASE_WORKING_DIR}; ${GUEST_TESTS_DIR}/${TEST_NAME} -c ${GUEST_BASE_WORKING_DIR}/config.base"
